---

CODE_ROOT: '/home/ubuntu/code/commcare-sync'
VIRTUALENV_ROOT: '/home/ubuntu/.virtualenvs/commcare-sync'
DJANGO_SETTINGS_MODULE: 'commcare_sync.local'
DJANGO_PROCESS: 'commcare-sync-django'
CELERY_PROCESS: 'commcare-sync-celery'

...
